[package]
name = "ldgerrits/loader"
description = "A lightweight services loader for the Roblox ecosystem adapted from Axis by Sleitnick"
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = [
    "default.project.json",
    "src",
    "src/**",
    "LICENSE",
    "README.md",
    "wally.toml",
]

[dependencies]
